### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by thelegitdolt** [Y3Z0N/ImmersiveFX#10]
<img width="1577" alt="Screen Shot 2022-06-12 at 3 37 19 PM" src="https://user-images.githubusercontent.com/50085439/173256369-1703ef80-9d38-4f06-8bdb-6cc4ee327372.png">
[crash-2022-06-12_15.37.13-client.txt](https://github.com/Y3Z0N/ImmersiveFX/files/8886924/crash-2022-06-12_15.37.13-client.txt)

**Comment by thelegitdolt** [comment]
https://gist.github.com/thelegitdolt/be1c736acb4b82480f88cbe5e6ff1abf

**Comment by Y3Z0N** [comment]
Will have a look

**Comment by brisingraerowing** [comment]
This is caused by a Forge change, and it's CTM crashing. There's a PR to redo the change in Forge that won't break things, though AFAIK it isn't merged yet.

**Comment by thelegitdolt** [comment]
yep can confirm, CTM problem not this
