### ISSUE TITLE
Error spam and poor performance

### ISSUE THREAD

**Issue by MattB70** [Y3Z0N/ImmersiveFX#14]
Error:
`[SoundControl Sound Processor/WARN]: SoundControl Sound Processor is lagging; behind 13 msecs`

Effect:
High CPU usage from the render thread even during hanging while loading.
Performance drops from >60fps to ~30fps during rain.
Can cause the game to hang on startup forever.

Here is a log where it happens during gameplay:
https://gist.github.com/MattB70/3bb50a38ab573bcb3dedc067f5f25e1a

This issue has already been discussed a little bit by Ranker on the main DynamicSurroundings repo here last year:
https://github.com/OreCruncher/DynamicSurroundings/issues/689

**Comment by Y3Z0N** [comment]
Tested on 1.18.2 & 1.16.5
Devices: Custom Build (Ryzen 5, 32GB Ram, RTX2060s), MacBook Pro 2016, MacBook Pro 2019.

tested on three deviced and i still could not reproduce the issue you mentioned. It looks more that your modpack was bad developed than an ImmersiveFX issue. It looks like you are:

- Using to much mods with sound sources
- Theres also a „not found“ spam of various mods im really concerned about that one


Also please give me some steps to reproduce.

**Comment by MattB70** [comment]
I removed the Ambient Sounds mod as it was hooking into the same things as this mod. This modpack version is literally hours old, so that's why its a mess.
