### ISSUE TITLE
Better fog control

### ISSUE THREAD

**Issue by E-daw** [Y3Z0N/ImmersiveFX#15]
Currently in the latest 1.16.5 version "1.0.2" optifine's fog start option doesn't effect the actual starting distance of the fog. 
Is it possible for the option to be added into the mod directly to allow for a customizable fog start distance similar to the option found in optifine?

**Comment by Y3Z0N** [comment]
not possible since optifine is closed source

**Comment by E-daw** [comment]
No no not a direct compatability option with optifine or anything I was just requesting a fog start distance configuration in the config file of this mod. completely seperate from optifine.
