### ISSUE TITLE
Rubidium

### ISSUE THREAD

**Issue by ghost** [Y3Z0N/ImmersiveFX#48]
Particle Culling
The Immersive Fx footprints are invisible
With the exception of version 1.19.2, the others seem to be the same.

**Comment by ghost** [comment]
The flat world can be seen, the ordinary world can not see, how strange.

**Comment by Kasualix** [comment]
This is fixed in Embeddium

**Comment by ghost** [comment]
> This is fixed in Embeddium

I know it's fixed and in use, thank you developers.
